INSERT INTO PUBLIC.CONSTELLATION(ID, NAME) VALUES
('and', 'Andromeda'),
('ant', 'Antlia'),
('aps', 'Apus'),
('aqr', 'Aquarius'),
('aql', 'Aquila'),
('ara', 'Ara'),
('ari', 'Aries'),
('aur', 'Auriga'),
('cnc', 'Cancer'),
('cma', 'Canis Major'),
('cap', 'Capricornus'),
('cas', 'Cassiopeia'),
('cru', 'Crux'),
('for', 'Fornax'),
('lib', 'Libra'),
('lyn', 'Lynx');

INSERT INTO PUBLIC.STAR(ID, NAME, CONSTELLATION_ID) VALUES
('1', 'Sirrah', 'and'),
('2', 'Mirach', 'and'),
('3', 'Almach', 'and'),
('4', 'Sadalmelik', 'aqr'),
('5', 'Sadalsuud', 'aqr'),
('6', 'Sirius', 'cma'),
('7', 'Theta', 'cma'),
('8', 'Schedar', 'cas'),
('9', 'Achird', 'cas'),
('10', 'Acrux', 'cru'),
('11', 'Fornacis', 'for'),
('12', 'Beta Fornacis', 'for'),
('13', 'Zubeneschamali', 'lib'),
('14', 'Gliese', 'lib'),
('15', 'Pleione', 'lib'),
('16', 'Elvashak', 'lyn'),
('17', 'Alsciaukat', 'lyn');
